services:
  backend:
    container_name: backend
    build:
      context: ./
    ports:
      - 8000:8000
    depends_on:
      db:
        condition:
          service_healthy
    env_file:
      - .env
    environment:
      - DB_HOST=db
    networks:
      - app-network

  db:
    image: postgres:latest
    restart: always
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    networks:
      - app-network
    volumes:
      - pg_data:/var/lib/postgresql/data

networks:
  app-network:
    driver: bridge
  
volumes:
  pg_data:

    