# Generated by Django 5.2.3 on 2025-07-01 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='stock',
            field=models.IntegerField(default=0, max_length=9),
            preserve_default=False,
        ),
    ]
