# Generated by Django 5.2.3 on 2025-07-14 22:37

import backend.core.validators.password
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=128, validators=[backend.core.validators.password.validate_min_length_8, backend.core.validators.password.validate_min_uppercase_1, backend.core.validators.password.validate_min_digits_3, backend.core.validators.password.validate_min_non_alphanumeric_1]),
        ),
    ]
